-- +goose Up
-- Webhooks: subscriptions and the delivery ledger with retry state.

CREATE TABLE webhooks (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    url             text NOT NULL,
    -- HMAC signing secret; generated by us, needed in clear to sign each
    -- delivery. Encrypt-at-rest is tracked for a later hardening pass.
    secret          text NOT NULL,
    events          text[] NOT NULL DEFAULT '{email.accepted,email.delivered_local,email.failed}',
    enabled         boolean NOT NULL DEFAULT true,
    created_by      uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX webhooks_tenant_idx ON webhooks (tenant_id);

CREATE TABLE webhook_deliveries (
    id               bigserial PRIMARY KEY,
    webhook_id       uuid NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,
    event_id         text NOT NULL, -- stable id, deduplicates NATS redelivery
    event_type       text NOT NULL,
    payload          jsonb NOT NULL,
    status           text NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending', 'delivered', 'failed')),
    attempts         int NOT NULL DEFAULT 0,
    next_attempt_at  timestamptz NOT NULL DEFAULT now(),
    last_status_code int,
    last_error       text NOT NULL DEFAULT '',
    delivered_at     timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (webhook_id, event_id)
);
CREATE INDEX webhook_deliveries_due_idx
    ON webhook_deliveries (next_attempt_at) WHERE status = 'pending';
CREATE INDEX webhook_deliveries_webhook_idx ON webhook_deliveries (webhook_id, created_at DESC);

-- +goose Down
DROP TABLE IF EXISTS webhook_deliveries;
DROP TABLE IF EXISTS webhooks;
