-- +goose Up
-- DKIM key registry (V4 §20-28). The control plane records WHICH keys exist
-- — selector, algorithm, public key, lifecycle — while the PRIVATE key is
-- generated by and lives only inside the mail core (its encrypted data
-- store), never in this database, never in logs, never in an API response
-- (§22). Rotation foundation (§28): active → previous with retire_after;
-- 'next' supports pre-publishing a DNS record before activation.

CREATE TABLE dkim_keys (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    domain_id    uuid NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
    selector     text NOT NULL,
    algorithm    text NOT NULL DEFAULT 'rsa' CHECK (algorithm IN ('rsa', 'ed25519')),
    public_key   text NOT NULL DEFAULT '',  -- base64 p= value for the DNS TXT
    status       text NOT NULL DEFAULT 'active'
                 CHECK (status IN ('active', 'next', 'previous', 'retired')),
    created_at   timestamptz NOT NULL DEFAULT now(),
    activated_at timestamptz,
    retire_after timestamptz,
    UNIQUE (domain_id, selector)
);
-- One live signing key per domain and algorithm.
CREATE UNIQUE INDEX dkim_keys_active_idx ON dkim_keys (domain_id, algorithm)
    WHERE status = 'active';
CREATE INDEX dkim_keys_domain_idx ON dkim_keys (domain_id);

-- +goose Down
DROP TABLE IF EXISTS dkim_keys;
